apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHMuYzltZWlnYWM2ZjM2LmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb20=
  db_username: YWRtaW4=
  db_password: c2ltb24xMjM=
