pipeline {
    agent any 

    stages {
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/simonxox/project2025.git'
            }
        }
        stage("Docker Image Build") {
            steps {
                script {
                    dir('client') {
                        sh 'docker system prune -f'
                        sh 'docker container prune -f'
                        sh 'docker build -t backend .'
                    }
                }
            }
        }
        stage("ECR Image Pushing") {
            steps {
                script {
                    sh '''
                    aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 324037320561.dkr.ecr.ap-south-1.amazonaws.com
                    docker tag frontend 324037320561.dkr.ecr.ap-south-1.amazonaws.com/frontend:${BUILD_NUMBER}
                    docker push 324037320561.dkr.ecr.ap-south-1.amazonaws.com/frontend:${BUILD_NUMBER}
                    '''
                }
            }
        }
        stage('Update Deployment file') {
            environment {
                GIT_REPO_NAME = "project2025"
                GIT_USER_NAME = "simonxox"
            }
            steps {
                dir('kubernetes-files') {
                    withCredentials([string(credentialsId: 'my-git-pattoken', variable: 'git_token')]) {
                        sh '''
                            git config user.email "simonchinnu13@gmail.com"
                            git config user.name "simonxox"
                            BUILD_NUMBER=${BUILD_NUMBER}
                            echo $BUILD_NUMBER
                            sed -i "s#image:.*#image: 324037320561.dkr.ecr.ap-south-1.amazonaws.com/frontend:$BUILD_NUMBER#g" frontend-deploy-service.yaml
                            git add .
                            git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
                            git push https://${git_token}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                        '''
                    }
                }
            }
        }
    }
}
